using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyCopyrightAttribute("Copyright Blue Bridge Solutions Ltd 2010")]
[assembly: AssemblyProductAttribute("CoSACS")]
[assembly: AssemblyCompanyAttribute("Blue Bridge Solutions, Ltd")]
[assembly: AssemblyVersionAttribute("10.7.4.12")]
[assembly: AssemblyFileVersionAttribute("10.7.4.12")]
[assembly: AssemblyInformationalVersionAttribute("10.7.4.12")]

